export const CITIES_BY_STATE = {
  AL: ['Birmingham','Montgomery','Huntsville','Mobile','Tuscaloosa','Hoover','Dothan','Auburn','Decatur','Madison','Florence','Phenix City'],
  AK: ['Anchorage','Fairbanks','Juneau','Sitka','Ketchikan','Wasilla','Kenai','Kodiak'],
  AZ: ['Phoenix','Tucson','Mesa','Chandler','Scottsdale','Gilbert','Tempe','Peoria','Surprise','Glendale','Flagstaff','Yuma','Avondale','Goodyear','Lake Havasu City','Prescott','Casa Grande'],
  AR: ['Little Rock','Fort Smith','Fayetteville','Springdale','Jonesboro','Conway','Rogers','Bentonville','Pine Bluff','Hot Springs','Texarkana'],
  CA: ['Los Angeles','San Diego','San Jose','San Francisco','Fresno','Sacramento','Long Beach','Oakland','Bakersfield','Anaheim','Santa Ana','Riverside','Stockton','Irvine','Chula Vista','Fremont','Modesto','San Bernardino','Santa Clarita','Fontana','Garden Grove','Oceanside','Moreno Valley','Huntington Beach','Glendale','Santa Rosa','Ontario','Rancho Cucamonga','Elk Grove','Corona','Lancaster','Salinas','Pomona','Torrance','Hayward','Escondido','Sunnyvale','Pasadena','Visalia','Roseville','Santa Barbara','Thousand Oaks','Concord','Simi Valley','Victorville','Vallejo','El Monte','Berkeley','Downey','Costa Mesa'],
  CO: ['Denver','Colorado Springs','Aurora','Fort Collins','Lakewood','Thornton','Arvada','Westminster','Pueblo','Centennial','Boulder','Highlands Ranch','Greeley','Longmont','Loveland','Broomfield','Castle Rock','Commerce City','Parker','Northglenn'],
  CT: ['Bridgeport','New Haven','Hartford','Stamford','Waterbury','Norwalk','Danbury','New Britain','Greenwich','West Hartford','Bristol','Meriden','New London'],
  DE: ['Wilmington','Dover','Newark','Middletown','Smyrna','Milford','Seaford','Georgetown'],
  FL: ['Jacksonville','Miami','Tampa','Orlando','St. Petersburg','Hialeah','Tallahassee','Fort Lauderdale','Port St. Lucie','Cape Coral','Pembroke Pines','Hollywood','Miramar','Gainesville','Coral Springs','Palm Bay','Clearwater','West Palm Beach','Lakeland','Pompano Beach','Davie','Miami Gardens','Boca Raton','Deltona','Sunrise','Plantation','Fort Myers','Palm Coast','Deerfield Beach','Melbourne','Kissimmee','Ocala','Pensacola','Sarasota','Brandon','Bradenton'],
  GA: ['Atlanta','Columbus','Augusta','Macon','Savannah','Athens','Sandy Springs','Roswell','Albany','Alpharetta','Marietta','Warner Robins','Smyrna','Peachtree City','Johns Creek','Valdosta','Dunwoody','South Fulton'],
  HI: ['Honolulu','Hilo','Kailua','Pearl City','Waipahu','Kaneohe','Mililani Town','Kahului','Kihei'],
  ID: ['Boise','Meridian','Nampa','Idaho Falls','Pocatello','Caldwell','Coeur d\'Alene','Twin Falls','Lewiston','Rexburg'],
  IL: ['Chicago','Aurora','Joliet','Naperville','Rockford','Springfield','Elgin','Peoria','Champaign','Waukegan','Cicero','Bloomington','Arlington Heights','Evanston','Decatur','Schaumburg','Bolingbrook','Palatine','Skokie','Des Plaines','Orland Park','Oak Park','Tinley Park','Berwyn'],
  IN: ['Indianapolis','Fort Wayne','Evansville','South Bend','Carmel','Fishers','Bloomington','Hammond','Gary','Muncie','Lafayette','Terre Haute','Noblesville','Kokomo','Anderson','Greenwood'],
  IA: ['Des Moines','Cedar Rapids','Davenport','Sioux City','Iowa City','Waterloo','Ames','West Des Moines','Dubuque','Ankeny','Urbandale','Cedar Falls','Waukee','Marion'],
  KS: ['Wichita','Overland Park','Kansas City','Topeka','Olathe','Lawrence','Shawnee','Manhattan','Lenexa','Salina','Hutchinson','Leavenworth'],
  KY: ['Louisville','Lexington','Bowling Green','Owensboro','Covington','Hopkinsville','Richmond','Florence','Georgetown','Henderson'],
  LA: ['New Orleans','Baton Rouge','Shreveport','Metairie','Lafayette','Lake Charles','Kenner','Bossier City','Monroe','Alexandria','Slidell','Prairieville'],
  ME: ['Portland','Lewiston','Bangor','South Portland','Auburn','Brunswick','Biddeford','Sanford','Augusta','Saco','Westbrook'],
  MD: ['Baltimore','Frederick','Rockville','Gaithersburg','Bowie','Hagerstown','Annapolis','College Park','Salisbury','Laurel','Greenbelt','Germantown','Silver Spring','Waldorf'],
  MA: ['Boston','Worcester','Springfield','Lowell','Cambridge','New Bedford','Brockton','Quincy','Lynn','Fall River','Newton','Somerville','Lawrence','Framingham','Haverhill','Waltham','Malden','Brookline','Plymouth','Taunton','Medford'],
  MI: ['Detroit','Grand Rapids','Warren','Sterling Heights','Ann Arbor','Lansing','Flint','Dearborn','Livonia','Westland','Troy','Farmington Hills','Clinton Township','Southfield','Kalamazoo','Pontiac','Rochester Hills','Saginaw','Muskegon','Holland'],
  MN: ['Minneapolis','Saint Paul','Rochester','Duluth','Bloomington','Brooklyn Park','Plymouth','Maple Grove','Woodbury','St. Cloud','Eagan','Coon Rapids','Eden Prairie','Burnsville','Apple Valley','Edina','Minnetonka'],
  MS: ['Jackson','Gulfport','Southaven','Hattiesburg','Biloxi','Meridian','Tupelo','Olive Branch','Horn Lake','Grenada'],
  MO: ['Kansas City','St. Louis','Springfield','Columbia','Independence','Lee\'s Summit','O\'Fallon','St. Joseph','St. Charles','Blue Springs','Joplin','Florissant','Chesterfield','Jefferson City'],
  MT: ['Billings','Missoula','Great Falls','Bozeman','Butte','Helena','Kalispell','Havre','Anaconda'],
  NE: ['Omaha','Lincoln','Bellevue','Grand Island','Kearney','Fremont','Hastings','North Platte','Norfolk','Papillion'],
  NV: ['Las Vegas','Henderson','Reno','North Las Vegas','Sparks','Carson City','Fernley','Elko','Mesquite'],
  NH: ['Manchester','Nashua','Concord','Derry','Dover','Rochester','Salem','Merrimack','Londonderry','Hudson','Keene'],
  NJ: ['Newark','Jersey City','Paterson','Elizabeth','Edison','Woodbridge','Lakewood','Toms River','Hamilton','Trenton','Clifton','Camden','Brick','Cherry Hill','Passaic','Union City','Bayonne','East Orange','Vineland'],
  NM: ['Albuquerque','Las Cruces','Rio Rancho','Santa Fe','Roswell','Farmington','Clovis','Hobbs','Alamogordo','Carlsbad'],
  NY: ['New York City','Buffalo','Rochester','Yonkers','Syracuse','Albany','New Rochelle','Mount Vernon','Schenectady','Utica','White Plains','Troy','Niagara Falls','Binghamton','Brooklyn','Queens','Bronx','Staten Island','Manhattan','Long Island','Hempstead','Amherst','Cheektowaga'],
  NC: ['Charlotte','Raleigh','Greensboro','Durham','Winston-Salem','Fayetteville','Cary','Wilmington','High Point','Concord','Greenville','Asheville','Gastonia','Jacksonville','Chapel Hill','Apex','Huntersville'],
  ND: ['Fargo','Bismarck','Grand Forks','Minot','West Fargo','Williston','Dickinson','Mandan'],
  OH: ['Columbus','Cleveland','Cincinnati','Toledo','Akron','Dayton','Parma','Canton','Youngstown','Lorain','Hamilton','Springfield','Kettering','Elyria','Lakewood','Cuyahoga Falls','Newark','Middletown'],
  OK: ['Oklahoma City','Tulsa','Norman','Broken Arrow','Lawton','Edmond','Moore','Midwest City','Enid','Stillwater','Muskogee','Bartlesville'],
  OR: ['Portland','Salem','Eugene','Gresham','Hillsboro','Beaverton','Bend','Medford','Springfield','Corvallis','Albany','Tigard','Lake Oswego','Keiser'],
  PA: ['Philadelphia','Pittsburgh','Allentown','Erie','Reading','Scranton','Bethlehem','Lancaster','Harrisburg','York','Altoona','Wilkes-Barre','Chester','Easton','State College'],
  RI: ['Providence','Warwick','Cranston','Pawtucket','East Providence','Woonsocket','Coventry','Cumberland','North Providence'],
  SC: ['Columbia','Charleston','North Charleston','Mount Pleasant','Rock Hill','Greenville','Summerville','Goose Creek','Hilton Head Island','Spartanburg','Florence','Myrtle Beach','Anderson','Aiken'],
  SD: ['Sioux Falls','Rapid City','Aberdeen','Brookings','Watertown','Mitchell','Huron','Vermillion'],
  TN: ['Nashville','Memphis','Knoxville','Chattanooga','Clarksville','Murfreesboro','Franklin','Johnson City','Bartlett','Hendersonville','Jackson','Kingsport','Smyrna','Collierville'],
  TX: ['Houston','San Antonio','Dallas','Austin','Fort Worth','El Paso','Arlington','Corpus Christi','Plano','Laredo','Lubbock','Garland','Irving','Amarillo','Grand Prairie','McKinney','Frisco','Mesquite','Killeen','McAllen','Waco','Carrollton','Denton','Midland','Abilene','Beaumont','Round Rock','Odessa','Richardson','The Woodlands','Pearland','Tyler','League City','Pasadena','Allen','Sugar Land','College Station','Brownsville','Lewisville','Edinburg','Conroe','Wichita Falls','San Angelo','Katy','Flower Mound','Longview','Pflugerville','New Braunfels','Mission','Missouri City','Pearland','Baytown','Cedar Park','Atascocita','Rowlett','Harlingen','Temple','Midland','Wichita Falls'],
  UT: ['Salt Lake City','West Valley City','Provo','West Jordan','Orem','Sandy','St. George','Ogden','Layton','South Jordan','Lehi','Millcreek','Taylorsville','Logan','Murray','Draper','Herriman'],
  VT: ['Burlington','South Burlington','Rutland','Essex Junction','Barre','Montpelier','Brattleboro'],
  VA: ['Virginia Beach','Norfolk','Chesapeake','Richmond','Newport News','Alexandria','Hampton','Roanoke','Portsmouth','Suffolk','Lynchburg','Harrisonburg','Charlottesville','Manassas','Fredericksburg','Arlington'],
  WA: ['Seattle','Spokane','Tacoma','Vancouver','Bellevue','Kent','Everett','Renton','Spokane Valley','Federal Way','Kirkland','Bellingham','Kennewick','Yakima','Redmond','Marysville','Pasco','Sammamish','South Hill'],
  WV: ['Charleston','Huntington','Morgantown','Parkersburg','Wheeling','Weirton','Beckley','Fairmont'],
  WI: ['Milwaukee','Madison','Green Bay','Kenosha','Racine','Appleton','Waukesha','Oshkosh','Eau Claire','Janesville','West Allis','La Crosse','Sheboygan','Fond du Lac','Wausau'],
  WY: ['Cheyenne','Casper','Laramie','Gillette','Rock Springs','Sheridan','Green River','Riverton'],
  DC: ['Washington'],
};
